#name: abraham_flutter_app
#description: "A new Flutter project."
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#
#version: 1.0.0+1
#
#environment:
#  sdk: '>=3.4.3 <4.0.0'
#
#dependencies:
#  flutter:
#    sdk: flutter
#  drift_sqflite: ^2.0.0  # última versión disponible al momento de escribir esto
#  provider: ^6.0.1
#  crypto: ^3.0.1
#  cupertino_icons: ^1.0.6
#
#  drift: any
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  drift_dev: ^2.0.0  # última versión disponible al momento de escribir esto
#  build_runner: ^2.1.5
#  flutter_lints: ^3.0.0
#  analyzer: ^4.7.0
#
#flutter:
#
#  uses-material-design: true

name: abraham_flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.0.0
  build_runner: ^2.1.5
  flutter_lints: ^4.0.0
  analyzer: ^6.4.1



flutter:
  uses-material-design: true

